from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(563, 512)
        Dialog.setStyleSheet("QDialog {\n"
"background: #d18d1e;\n"
"}\n"
"\n"
"QPushButton {\n"
"background: #d18d1e;\n"
"border: 1px solid #7f3a19;\n"
"border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #e0b401;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background: #3a2b10;\n"
"}\n"
"\n"
"QLineEdit {\n"
"background: #a6b6ab;\n"
"}\n"
"\n"
"QTextEdit {\n"
"background: #a6b6ab;\n"
"}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 110, 501, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout.addWidget(self.pushButton_13)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 111, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_14 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_2.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_2.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_2.addWidget(self.pushButton_16)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 190, 501, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_18 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_3.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_3.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_3.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_3.addWidget(self.pushButton_21)
        self.pushButton_22 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_3.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_3.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_3.addWidget(self.pushButton_24)
        self.pushButton_25 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_3.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_3.addWidget(self.pushButton_26)
        self.pushButton_27 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_3.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_3.addWidget(self.pushButton_28)
        self.pushButton_29 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_3.addWidget(self.pushButton_29)
        self.pushButton_30 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_3.addWidget(self.pushButton_30)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 270, 501, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_31 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_4.addWidget(self.pushButton_31)
        self.pushButton_32 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_4.addWidget(self.pushButton_32)
        self.pushButton_33 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_4.addWidget(self.pushButton_33)
        self.pushButton_34 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_4.addWidget(self.pushButton_34)
        self.pushButton_35 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_4.addWidget(self.pushButton_35)
        self.pushButton_36 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_4.addWidget(self.pushButton_36)
        self.pushButton_37 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_4.addWidget(self.pushButton_37)
        self.pushButton_38 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayout_4.addWidget(self.pushButton_38)
        self.pushButton_39 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_4.addWidget(self.pushButton_39)
        self.pushButton_40 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_40.setObjectName("pushButton_40")
        self.horizontalLayout_4.addWidget(self.pushButton_40)
        self.pushButton_41 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_41.setObjectName("pushButton_41")
        self.horizontalLayout_4.addWidget(self.pushButton_41)
        self.pushButton_42 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_42.setObjectName("pushButton_42")
        self.horizontalLayout_4.addWidget(self.pushButton_42)
        self.pushButton_43 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_43.setObjectName("pushButton_43")
        self.horizontalLayout_4.addWidget(self.pushButton_43)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 110, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 270, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(30, 350, 501, 80))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_44 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_44.setObjectName("pushButton_44")
        self.horizontalLayout_5.addWidget(self.pushButton_44)
        self.pushButton_45 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_45.setObjectName("pushButton_45")
        self.horizontalLayout_5.addWidget(self.pushButton_45)
        self.pushButton_46 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_46.setObjectName("pushButton_46")
        self.horizontalLayout_5.addWidget(self.pushButton_46)
        self.pushButton_47 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_47.setObjectName("pushButton_47")
        self.horizontalLayout_5.addWidget(self.pushButton_47)
        self.pushButton_48 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_48.setObjectName("pushButton_48")
        self.horizontalLayout_5.addWidget(self.pushButton_48)
        self.pushButton_49 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_49.setObjectName("pushButton_49")
        self.horizontalLayout_5.addWidget(self.pushButton_49)
        self.pushButton_50 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_50.setObjectName("pushButton_50")
        self.horizontalLayout_5.addWidget(self.pushButton_50)
        self.pushButton_51 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_51.setObjectName("pushButton_51")
        self.horizontalLayout_5.addWidget(self.pushButton_51)
        self.pushButton_52 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_52.setObjectName("pushButton_52")
        self.horizontalLayout_5.addWidget(self.pushButton_52)
        self.pushButton_53 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_53.setObjectName("pushButton_53")
        self.horizontalLayout_5.addWidget(self.pushButton_53)
        self.pushButton_54 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_54.setObjectName("pushButton_54")
        self.horizontalLayout_5.addWidget(self.pushButton_54)
        self.pushButton_55 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_55.setObjectName("pushButton_55")
        self.horizontalLayout_5.addWidget(self.pushButton_55)
        self.pushButton_56 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_56.setObjectName("pushButton_56")
        self.horizontalLayout_5.addWidget(self.pushButton_56)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 350, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_57 = QtWidgets.QPushButton(Dialog)
        self.pushButton_57.setGeometry(QtCore.QRect(190, 450, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_57.setFont(font)
        self.pushButton_57.setObjectName("pushButton_57")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "2"))
        self.pushButton_2.setText(_translate("Dialog", "3"))
        self.pushButton_3.setText(_translate("Dialog", "4"))
        self.pushButton_4.setText(_translate("Dialog", "5"))
        self.pushButton_5.setText(_translate("Dialog", "6"))
        self.pushButton_6.setText(_translate("Dialog", "7"))
        self.pushButton_7.setText(_translate("Dialog", "8"))
        self.pushButton_8.setText(_translate("Dialog", "9"))
        self.pushButton_9.setText(_translate("Dialog", "10"))
        self.pushButton_10.setText(_translate("Dialog", "В"))
        self.pushButton_11.setText(_translate("Dialog", "Д"))
        self.pushButton_12.setText(_translate("Dialog", "К"))
        self.pushButton_13.setText(_translate("Dialog", "Т"))
        self.pushButton_14.setText(_translate("Dialog", "24"))
        self.pushButton_15.setText(_translate("Dialog", "36"))
        self.pushButton_16.setText(_translate("Dialog", "52"))
        self.pushButton_18.setText(_translate("Dialog", "2"))
        self.pushButton_19.setText(_translate("Dialog", "3"))
        self.pushButton_20.setText(_translate("Dialog", "4"))
        self.pushButton_21.setText(_translate("Dialog", "5"))
        self.pushButton_22.setText(_translate("Dialog", "6"))
        self.pushButton_23.setText(_translate("Dialog", "7"))
        self.pushButton_24.setText(_translate("Dialog", "8"))
        self.pushButton_25.setText(_translate("Dialog", "9"))
        self.pushButton_26.setText(_translate("Dialog", "10"))
        self.pushButton_27.setText(_translate("Dialog", "В"))
        self.pushButton_28.setText(_translate("Dialog", "Д"))
        self.pushButton_29.setText(_translate("Dialog", "К"))
        self.pushButton_30.setText(_translate("Dialog", "Т"))
        self.pushButton_31.setText(_translate("Dialog", "2"))
        self.pushButton_32.setText(_translate("Dialog", "3"))
        self.pushButton_33.setText(_translate("Dialog", "4"))
        self.pushButton_34.setText(_translate("Dialog", "5"))
        self.pushButton_35.setText(_translate("Dialog", "6"))
        self.pushButton_36.setText(_translate("Dialog", "7"))
        self.pushButton_37.setText(_translate("Dialog", "8"))
        self.pushButton_38.setText(_translate("Dialog", "9"))
        self.pushButton_39.setText(_translate("Dialog", "10"))
        self.pushButton_40.setText(_translate("Dialog", "В"))
        self.pushButton_41.setText(_translate("Dialog", "Д"))
        self.pushButton_42.setText(_translate("Dialog", "К"))
        self.pushButton_43.setText(_translate("Dialog", "Т"))
        self.label.setText(_translate("Dialog", "♣"))
        self.label_2.setText(_translate("Dialog", "♥"))
        self.label_3.setText(_translate("Dialog", "♠"))
        self.pushButton_44.setText(_translate("Dialog", "2"))
        self.pushButton_45.setText(_translate("Dialog", "3"))
        self.pushButton_46.setText(_translate("Dialog", "4"))
        self.pushButton_47.setText(_translate("Dialog", "5"))
        self.pushButton_48.setText(_translate("Dialog", "6"))
        self.pushButton_49.setText(_translate("Dialog", "7"))
        self.pushButton_50.setText(_translate("Dialog", "8"))
        self.pushButton_51.setText(_translate("Dialog", "9"))
        self.pushButton_52.setText(_translate("Dialog", "10"))
        self.pushButton_53.setText(_translate("Dialog", "В"))
        self.pushButton_54.setText(_translate("Dialog", "Д"))
        self.pushButton_55.setText(_translate("Dialog", "К"))
        self.pushButton_56.setText(_translate("Dialog", "Т"))
        self.label_4.setText(_translate("Dialog", "♦"))
        self.pushButton_57.setText(_translate("Dialog", "Новая игра"))
